### ISSUE TITLE
Gem::ConflictError with new released cocoapods-downloader-2.0

### ISSUE THREAD

**Issue by BenjaminZaiser** [microsoft/cocoapods-azure-universal-packages#12]
Hi,

since last week everything was working fine, but unfortunately on 2023-10-26 cocoapods-downloader was released in version 2.0, see https://rubygems.org/gems/cocoapods-downloader/versions/2.0

Since then I get this error when running pod install:
`Gem::ConflictError - Unable to activate cocoapods-azure-universal-packages-0.1.0, because cocoapods-downloader-2.0 conflicts with cocoapods-downloader (~> 1.0)`

I guess in https://github.com/microsoft/cocoapods-azure-universal-packages/blob/main/cocoapods-azure-universal-packages.gemspec the runtime version dependency to cocoapods-downloader should be updated to 2.0 to stay compatible!?

Please can you try to have a look and fix it?

Thanks
Ben

**Comment by BenjaminZaiser** [comment]
Note: a workaround could be to run
`gem install "cocoapods-downloader" -v 1.0`
before building an app.

**Comment by Manojkumar-Subramaniam** [comment]
I too face this issue. Did `gem install cocoapods-downloader -v 1.6.3` in appcenter-pre-build.sh but still facing this issue.

**Comment by Frugghi** [comment]
@zflorin Unfortunately I'm no longer at Microsoft so I don't have write permissions to this repo anymore. I'll reach out to some of my ex-colleagues to see if anyone can help!

**Comment by zflorin** [comment]
> @zflorin Unfortunately I'm no longer at Microsoft so I don't have write permissions to this repo anymore. I'll reach out to some of my ex-colleagues to see if anyone can help!

That would be very much appreciated so thanks a bunch @Frugghi 💪🏻
